# Generated by Django 5.2.8 on 2025-11-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ETI MIS Platform', max_length=100)),
                ('academic_year', models.CharField(default='2025/2026', max_length=9)),
                ('allow_registration', models.BooleanField(default=True)),
            ],
        ),
    ]
