# Generated by Django 5.2.8 on 2026-03-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_supportticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('fixed', 'Fixed'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
