# Generated by Django 5.2.8 on 2026-05-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_supportticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='category',
            field=models.CharField(choices=[('system', 'System'), ('auth', 'Authentication'), ('registration', 'Registration'), ('assessment', 'Assessment'), ('resource', 'Resource'), ('finance', 'Finance')], default='system', max_length=50),
        ),
    ]
