# Generated by Django 5.2.8 on 2025-11-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('dean', 'Dean/HOD'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], max_length=10),
        ),
    ]
