# Generated by Django 5.2.8 on 2026-07-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='backlog_arrears',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Temporal arrears amount for backlog student upload', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_backlog',
            field=models.BooleanField(default=False, help_text='Designates if payment record originated from backlog upload'),
        ),
    ]
