# Generated by Django 5.2.8 on 2025-11-19 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_delete_payment'),
        ('users', '0004_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step1_completed', models.BooleanField(default=False)),
                ('step2_completed', models.BooleanField(default=False)),
                ('step3_completed', models.BooleanField(default=False)),
                ('step4_completed', models.BooleanField(default=False)),
                ('is_submitted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.academicyear')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.semester')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
