# Generated by Django 5.2.8 on 2025-11-19 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_delete_payment'),
        ('users', '0005_registrationprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationprogress',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.program'),
        ),
    ]
