# Generated by Django 5.2.8 on 2025-12-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_pin_code_customuser_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='level',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
