# Generated by Django 5.2.8 on 2025-12-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_level_studentregistration_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='generated_student_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
