# Generated by Django 5.2.8 on 2025-12-06 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_alter_enrollment_unique_together_enrollment_level_and_more'),
        ('users', '0010_alter_payment_generated_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_in_level', to='academics.programlevel'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_level', to='academics.programlevel'),
        ),
    ]
