# Generated by Django 5.2.8 on 2025-12-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0022_enrollment_payment'),
        ('users', '0011_alter_customuser_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='courses',
            field=models.ManyToManyField(related_name='registered_students', to='academics.programcourse'),
        ),
    ]
