# Generated by Django 5.2.8 on 2025-12-30 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('finance', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentbreakdown',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='users.payment'),
        ),
        migrations.AddField(
            model_name='programfee',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='programfee',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role': 'finance'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programfee',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.program'),
        ),
        migrations.AddField(
            model_name='programfee',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester'),
        ),
        migrations.AddField(
            model_name='programfeecomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_component_links', to='finance.feecomponent'),
        ),
        migrations.AddField(
            model_name='programfeecomponent',
            name='program_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_fee_components', to='finance.programfee'),
        ),
        migrations.AddField(
            model_name='programfee',
            name='components',
            field=models.ManyToManyField(related_name='program_fees', through='finance.ProgramFeeComponent', to='finance.feecomponent'),
        ),
        migrations.AddField(
            model_name='paymentbreakdown',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.programfeecomponent'),
        ),
        migrations.AlterUniqueTogether(
            name='programfeecomponent',
            unique_together={('program_fee', 'component')},
        ),
        migrations.AlterUniqueTogether(
            name='programfee',
            unique_together={('academic_year', 'semester', 'program')},
        ),
        migrations.AlterUniqueTogether(
            name='paymentbreakdown',
            unique_together={('payment', 'component')},
        ),
    ]
