# Generated by Django 5.2.8 on 2025-12-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        ('finance', '0003_seed_fee_components'),
    ]

    operations = [
    ]
