# Generated by Django 5.2.8 on 2026-05-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_applicationform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('acknowledged', 'Acknowledged')], default='pending', max_length=20),
        ),
    ]
