# Generated by Django 5.2.8 on 2026-05-06 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_studentoverpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentoverpayment',
            name='is_reimbursed',
            field=models.BooleanField(default=False, help_text='Set to True by Admin once the student has been physically paid back.'),
        ),
        migrations.AddField(
            model_name='studentoverpayment',
            name='reimbursed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentoverpayment',
            name='reimbursement_requested',
            field=models.BooleanField(default=False, help_text='Set to True when Finance requests a refund for the student.'),
        ),
        migrations.AddField(
            model_name='studentoverpayment',
            name='reimbursement_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentoverpayment',
            name='reimbursement_requested_by',
            field=models.ForeignKey(blank=True, help_text='The Finance staff member who initiated the refund request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
