# Generated by Django 5.2.8 on 2026-05-06 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_studentoverpayment_reimbursement_fields'),
        ('users', '0002_payment_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentoverpayment',
            name='is_used',
            field=models.BooleanField(default=False, help_text='Set to True when this credit is used to pay for a future fee.'),
        ),
        migrations.AddField(
            model_name='studentoverpayment',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentoverpayment',
            name='used_for_payment',
            field=models.ForeignKey(blank=True, help_text='The new payment record where this credit was applied.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilized_overpayments', to='users.payment'),
        ),
    ]
