# Generated by Django 5.2.8 on 2026-05-06 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_studentoverpayment_utilization_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='deletion_requested',
            field=models.BooleanField(default=False, help_text='Finance requested to delete/archive this record.'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='deletion_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_deletion_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Soft delete/Archive. Hides transaction from standard views.'),
        ),
    ]
