# Generated by Django 5.2.8 on 2026-05-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_banktransaction_deletion_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecomponent',
            name='code',
            field=models.CharField(default='code', help_text='Unique generated code for the fee component', max_length=50),
        ),
    ]
