# Generated by Django 5.2.8 on 2026-05-07 10:12

import random
from django.db import migrations

def generate_codes(apps, schema_editor):
    FeeComponent = apps.get_model('finance', 'FeeComponent')
    for component in FeeComponent.objects.filter(code='code'):
        letters = "".join([word[0] for word in component.name.split() if word]).upper()
        if len(letters) == 1:
            letters = component.name[:3].upper()
            
        while True:
            d1 = str(random.randint(0, 9))
            d2 = str(random.randint(0, 9))
            new_code = f"{d1}{letters}{d2}"
            if not FeeComponent.objects.filter(code=new_code).exclude(pk=component.pk).exists():
                component.code = new_code
                component.save()
                break

class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_feecomponent_code'),
    ]

    operations = [
        migrations.RunPython(generate_codes, reverse_code=migrations.RunPython.noop),
    ]
