# Generated by Django 5.2.8 on 2026-05-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_auto_20260507_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feecomponent',
            name='code',
            field=models.CharField(default='code', editable=False, help_text='Unique generated code for the fee component', max_length=50),
        ),
    ]
