# Generated by Django 5.2.8 on 2026-05-08 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_alter_feecomponent_code'),
        ('users', '0002_payment_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentoverpayment',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overpayments', to='users.payment'),
        ),
    ]
