# Generated by Django 5.2.8 on 2026-05-09 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_semester_unique_together'),
        ('finance', '0015_alter_studentoverpayment_payment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programfee',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='programfee',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.programlevel'),
        ),
        migrations.AlterUniqueTogether(
            name='programfee',
            unique_together={('academic_year', 'semester', 'program', 'level')},
        ),
    ]
