# Generated by Django 5.2.8 on 2026-07-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_alter_programfee_unique_together_programfee_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_prefix', models.CharField(max_length=50)),
                ('ip_address', models.CharField(max_length=45)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['key_prefix', 'ip_address', 'timestamp'], name='finance_rat_key_pre_b118b4_idx')],
            },
        ),
    ]
