# Generated by Django 5.2.8 on 2025-12-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_remove_transcript_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='school_signature/'),
        ),
        migrations.AddField(
            model_name='school',
            name='signee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
