# Generated by Django 5.2.8 on 2025-12-30 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['lecturer', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmenttask',
            name='assessment_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='academics.assessmentcategory'),
        ),
        migrations.AddField(
            model_name='assessmenttask',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['lecturer', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessment_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmenttaskscore',
            name='recorded_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['lecturer', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_scores_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmenttaskscore',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_task_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmenttaskscore',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='academics.assessmenttask'),
        ),
        migrations.AddField(
            model_name='assessmenttask',
            name='assessment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='academics.assessmenttype'),
        ),
        migrations.AddField(
            model_name='course',
            name='assigned_lecturers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'lecturer'}, related_name='courses_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseannouncement',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='dean',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'dean'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.department'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_payment', to='users.payment'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='academics.department'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_semesters', to='academics.program'),
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.program'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.program'),
        ),
        migrations.AddField(
            model_name='programcourse',
            name='assigned_lecturers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'lecturer'}, related_name='program_courses_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programcourse',
            name='base_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_variants', to='academics.course'),
        ),
        migrations.AddField(
            model_name='programcourse',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_courses', to='academics.program'),
        ),
        migrations.AddField(
            model_name='courseannouncement',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='academics.programcourse'),
        ),
        migrations.AddField(
            model_name='assessmenttask',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_tasks', to='academics.programcourse'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.programcourse'),
        ),
        migrations.AddField(
            model_name='programlevel',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='academics.program'),
        ),
        migrations.AddField(
            model_name='programcourse',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_courses', to='academics.programlevel'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.programlevel'),
        ),
        migrations.AddField(
            model_name='resource',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='academics.programcourse'),
        ),
        migrations.AddField(
            model_name='resource',
            name='lecturer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'lecturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='semester',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='semester',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.programlevel'),
        ),
        migrations.AddField(
            model_name='resource',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='programcourse',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_courses', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester'),
        ),
        migrations.AddField(
            model_name='assessmenttask',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_tasks', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='transcriptrequest',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='transcript_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='assessmenttaskscore',
            unique_together={('task', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='programcourse',
            unique_together={('program', 'level', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='assessmenttask',
            unique_together={('course', 'semester', 'assessment_type', 'assessment_category', 'title')},
        ),
    ]
