# Generated by Django 5.2.8 on 2026-03-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_seed_assessment_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='grade',
            field=models.CharField(help_text='Final grade obtained for the course (e.g., A, B+, C, N/A)', max_length=5),
        ),
    ]
