# Generated by Django 5.2.8 on 2025-11-16 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_remove_program_created_by_department_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='dean',
        ),
        migrations.AddField(
            model_name='department',
            name='dean',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'dean'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs_managed', to=settings.AUTH_USER_MODEL),
        ),
    ]
