# Generated by Django 5.2.8 on 2025-11-16 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_remove_program_dean_department_dean'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='courses',
                to='academics.department',
                null=True,
                blank=True,
            ),
        ),
        migrations.AlterField(
            model_name='course',
            name='credit_hours',
            field=models.IntegerField(default=3),
        ),
    ]

