# Generated by Django 5.2.8 on 2026-05-08 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_remove_assessment_is_allowed_assessment_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('name', 'academic_year', 'level')},
        ),
    ]
