# Generated by Django 5.2.8 on 2025-11-19 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_assessment_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
