# Generated by Django 5.2.8 on 2025-11-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=3, unique=True)),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ['-min_score'],
            },
        ),
    ]
