# Generated by Django 5.2.8 on 2025-11-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='sem_reg_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
