# Generated by Django 5.2.8 on 2025-12-05 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_resource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_requests', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='award_type',
            field=models.CharField(choices=[('certificate', 'Certificate'), ('diploma', 'Diploma'), ('hnd', 'Higher National Diploma'), ('bachelor', 'Bachelor Degree'), ('master', 'Masters'), ('phd', 'PhD')], default='bachelor', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='duration_years',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='program',
            name='semesters_per_level',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.CreateModel(
            name='ProgramLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=1)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='academics.program')),
            ],
        ),
        migrations.AddField(
            model_name='semester',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.programlevel'),
        ),
        migrations.CreateModel(
            name='TranscriptRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('transcript_json', models.JSONField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='transcript_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
