# Generated by Django 5.2.8 on 2025-12-06 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_transcriptsettings_program_award_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester'),
        ),
        migrations.AlterField(
            model_name='transcriptrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Access Revoked')], default='pending', max_length=20),
        ),
    ]
