# Generated by Django 5.2.8 on 2025-12-06 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_alter_course_semester'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'semester')},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.programlevel'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='program',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='program_semesters', to='academics.program'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
    ]
