# Generated by Django 5.2.8 on 2025-12-07 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_alter_enrollment_unique_together_enrollment_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.CreateModel(
            name='ProgramCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('credit_hours', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_variants', to='academics.course')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_courses', to='academics.programlevel')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_courses', to='academics.program')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_courses', to='academics.semester')),
            ],
            options={
                'ordering': ['program__name', 'level__order', 'title'],
                'unique_together': {('program', 'level', 'title')},
            },
        ),
    ]
