# Generated by Django 5.2.8 on 2025-12-07 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_remove_course_semester_programcourse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='programcourse',
            name='assigned_lecturers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'lecturer'}, related_name='program_courses_taught', to=settings.AUTH_USER_MODEL),
        ),
    ]
