# Generated by Django 5.2.8 on 2025-12-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0020_programcourse_assigned_lecturers'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
