# Generated by Django 5.2.8 on 2025-12-07 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_enrollment_is_current'),
        ('users', '0011_alter_customuser_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='payment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_payment', to='users.payment'),
            preserve_default=False,
        ),
    ]
