# Generated by Django 5.2.8 on 2025-12-08 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0023_alter_resource_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.programcourse'),
        ),
    ]
