# Generated by Django 5.2.8 on 2025-12-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0024_alter_assessment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration_years',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
