# Generated by Django 5.2.8 on 2025-12-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0025_academicyear_is_ready_alter_program_duration_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='name',
            field=models.CharField(help_text='Format: 2024/2025', max_length=16, unique=True),
        ),
    ]
